[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "precursorupdater"
authors = [
    {name="bunnie"}
]
version = "0.0.1"
description = "Precursor USB Updater"
license = { file="LICENSE" }
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "requests >= 2",
    "pyusb >= 1",
    "progressbar2 >= 3",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Topic :: System :: Hardware",
    "Topic :: System :: Hardware :: Universal Serial Bus (USB)",
]

[project.urls]
"Homepage" = "https://github.com/betrusted-io/betrusted-wiki/wiki/Updating-Your-Device"
"Bug Tracker" = "https://github.com/betrusted-io/xous-core/issues"

[tools.setuptools]
packages = ["precursorupdater"]

[project.scripts]
my-script = "precursorupdater.precursorupdater:main"
