[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "precursor_updater"
version = "0.0.1"
dependencies = [
    "requests",
    "pyusb",
    "progressbar2",
    "csv",
    "hashlib",
    'importlib-metadata; python_version<"3.8"',
]