[package]
authors = ["Sean Cross <sean@xobs.io>"]
description = "Log output program"
edition = "2018"
name = "xous-log"
version = "0.1.9"
license = "MIT OR Apache-2.0"
repository = "https://github.com/betrusted-io/xous-core/"
homepage = "https://betrusted.io/xous-book/"

# Dependency versions enforced by Cargo.lock.
[dependencies]
xous-api-log = {package = "xous-api-log", path = "../../api/xous-api-log"}
xous = { path = "../../xous-rs" }
xous-ipc = { path = "../../xous-ipc" }
log = "0.4.14"
num-derive = {version = "0.3.3", default-features = false}
num-traits = {version = "0.2.14", default-features = false}

utralib = {path = "../../utralib", optional = true, default-features = false }

[features]
precursor = ["utralib/precursor", "xous/precursor"]
hosted = ["utralib/hosted"]
renode = ["utralib/renode", "xous/renode"]
debugprint = [] # adding this allocates the UART for debugging the logger
logging = [] # adding this allocates the hardware UART for console interactions
#default = []
default = ["logging"]
# default = ["debugprint", "logging"]
