[package]
name = "benchmark-target"
version = "0.1.0"
authors = ["bunnie <bunnie@kosagi.com>"]
edition = "2018"
description = "Benchmark target for Xous"

# Dependency versions enforced by Cargo.lock.
[dependencies]
xous = { path = "../../xous-rs" }
xous-names = { path = "../xous-names" }
log-server = { version = "0.1.1", package = "xous-api-log-server" }
log = "0.4.14"

xous-ipc = {path = "../../xous-ipc"}
num-derive = {version = "0.3.3", default-features = false}
num-traits = {version = "0.2.14", default-features = false}
rkyv = {version = "0.4.3", default-features = false, features = ["const_generics"]}

[target.'cfg(not(any(windows,unix)))'.dependencies]
utralib = { path = "../../utralib"}

[features]
debugprint = []
# default = ["debugprint"] # "debugprint"
default = []
