[package]
name = "jtag"
version = "0.1.0"
authors = ["bunnie <bunnie@kosagi.com>"]
edition = "2018"
description = "JTAG port server"

# Dependency versions enforced by Cargo.lock.
[dependencies]
xous = "0.9.9"
log-server = { version = "0.1.2", package = "xous-api-log-server" }
ticktimer-server = { path = "../ticktimer-server" }
xous-names = { path = "../xous-names" }
log = "0.4.14"
num-derive = {version = "0.3.3", default-features = false}
num-traits = {version = "0.2.14", default-features = false}
susres = {path = "../susres"}

xous-ipc = "0.9.9"
rkyv = {version = "0.4.3", default-features = false, features = ["const_generics"]}

[target.'cfg(not(any(windows,unix)))'.dependencies]
utralib = { path = "../../utralib", default-features = false }

[features]
hazardous-debug = []
default = ["hazardous-debug"]
