[package]
name = "xous-riscv"
version = "0.5.6"
repository = "https://github.com/rust-embedded/riscv"
authors = ["The RISC-V Team <risc-v@teams.rust-embedded.org>"]
categories = ["embedded", "hardware-support", "no-std"]
description = "Low level access to RISC-V processors; Xous fork"
keywords = ["riscv", "register", "peripheral"]
license = "ISC"

# Dependency versions enforced by Cargo.lock.
[dependencies]
bare-metal = ">=0.2.0,<0.2.5"
bit_field = "0.9.0"

[features]
inline-asm = []