[package]
authors = ["bunnie <bunnie@kosagi.com>"]
description = "Provide high-resolution, non-rollover system time"
edition = "2018"
name = "xous-ticktimer"
version = "0.1.12"
license = "MIT OR Apache-2.0"
repository = "https://github.com/betrusted-io/xous-core/"
homepage = "https://betrusted.io/xous-book/"

# Dependency versions enforced by Cargo.lock.
[dependencies]
xous-api-ticktimer = { path = "../../api/xous-api-ticktimer" }
xous = { path = "../../xous-rs" }
xous-ipc = { path = "../../xous-ipc" }
xous-names = {package = "xous-api-names", path = "../../api/xous-api-names"}
log-server = {package = "xous-api-log", path = "../../api/xous-api-log"}
susres = {package = "xous-api-susres", path = "../../api/xous-api-susres"}
log = "0.4.14"
rkyv = {version = "0.4.3", default-features = false, features = ["const_generics"]}
num-derive = {version = "0.3.3", default-features = false}
num-traits = {version = "0.2.14", default-features = false}
xous-semver = "0.1.2"
utralib = {path = "../../utralib", optional = true, default-features = false }

[features]
precursor = ["utralib/precursor", "xous/precursor", "susres/precursor"]
hosted = ["utralib/hosted", "susres/hosted"]
renode = ["utralib/renode", "xous/renode", "susres/renode"]
debug-print = []
watchdog = []
timestamp = []
# you may want to remove the watchdog feature if you're debugging a crash, as it will force the system to reboot automatically
default = ["watchdog"]
# default = []
# default = ["debug-print"]
