[package]
name = "ffi-test"
version = "0.1.0"
authors = ["bunnie <bunnie@kosagi.com>"]
edition = "2018"
description = "FFI test integration"

# Dependency versions enforced by Cargo.lock.
[dependencies]
xous = { path = "../../xous-rs" }
log-server = { package = "xous-api-log", path = "../../api/xous-api-log" }
ticktimer-server = { package = "xous-api-ticktimer", path = "../../api/xous-api-ticktimer" }
xous-names = { package = "xous-api-names", path = "../../api/xous-api-names" }
log = "0.4.14"
num-derive = {version = "0.3.3", default-features = false}
num-traits = {version = "0.2.14", default-features = false}
susres = {package = "xous-api-susres", path = "../../api/xous-api-susres"}
ffi-sys = {path = "sys"}
keyboard = {path = "../keyboard"}

utralib = { path = "../../utralib", optional = true, default-features = false }

[features]
precursor = ["utralib/precursor", "xous/precursor"]
hosted = ["utralib/hosted"]
renode = ["utralib/renode", "xous/renode"]
default = []
