[package]
authors = ["Sean Cross <sean@xobs.io>"]
description = "Log output program"
edition = "2018"
name = "log-server"
version = "0.1.0"

# Dependency versions enforced by Cargo.lock.
[dependencies]
xous-api-log-server = {version = "0.1.1", package = "xous-api-log-server"}
log = "0.4.14"
num-derive = {version = "0.3.3", default-features = false}
num-traits = {version = "0.2.14", default-features = false}
xous = "0.9.9"
xous-ipc = "0.9.7"

[target.'cfg(not(any(windows,unix)))'.dependencies]
utralib = {path = "../../utralib"}

[features]
debugprint = [] # adding this allocates the UART for debugging the logger
logging = [] # adding this allocates the hardware UART for console interactions
#default = []
default = ["logging"]
# default = ["debugprint", "logging"]
