[package]
name = "spinor"
version = "0.1.0"
authors = ["bunnie <bunnie@kosagi.com>"]
edition = "2018"
description = "SPINOR ROM operations server"

# Dependency versions enforced by Cargo.lock.
[dependencies]
xous = { path = "../../xous-rs" }
log-server = { package = "xous-api-log", path = "../../api/xous-api-log" }
ticktimer-server = { package = "xous-api-ticktimer", path = "../../api/xous-api-ticktimer" }
xous-names = { package = "xous-api-names", path = "../../api/xous-api-names" }
log = "0.4.14"
susres = {package = "xous-api-susres", path = "../../api/xous-api-susres"}
trng = { path = "../trng" }
com = { path = "../com" }
llio = { path = "../llio" }

rkyv = {version = "0.4.3", default-features = false, features = ["const_generics"]}
xous-ipc = { path = "../../xous-ipc" }
num-derive = {version = "0.3.3", default-features = false}
num-traits = {version = "0.2.14", default-features = false}

utralib = { path = "../../utralib", optional = true, default-features = false }

[dev-dependencies]
lazy_static = "1.4.0"
rand = "0.7.3"

[features]
precursor = ["utralib/precursor", "xous/precursor"]
hosted = ["utralib/hosted"]
renode = ["utralib/renode", "xous/renode"]
extra_flush = []
default = []

[lib]
test = true

[[bin]]
name = "spinor"
test = false