[package]
name = "spinor"
version = "0.1.0"
authors = ["bunnie <bunnie@kosagi.com>"]
edition = "2018"
description = "SPINOR ROM operations server"

# Dependency versions enforced by Cargo.lock.
[dependencies]
xous = "0.9.9"
log-server = { version = "0.1.2", package = "xous-api-log-server" }
ticktimer-server = { path = "../ticktimer-server" }
xous-names = { path = "../xous-names" }
log = "0.4.14"
susres = {path = "../susres"}
trng = { path = "../trng" }
com = { path = "../com" }
llio = { path = "../llio" }

rkyv = {version = "0.4.3", default-features = false, features = ["const_generics"]}
xous-ipc = "0.9.9"
num-derive = {version = "0.3.3", default-features = false}
num-traits = {version = "0.2.14", default-features = false}

[target.'cfg(not(any(windows,unix)))'.dependencies]
utralib = { path = "../../utralib"}

[dev-dependencies]
lazy_static = "1.4.0"
rand = "0.7.3"

[features]
default = []

[lib]
test = true

[[bin]]
name = "spinor"
test = false