[package]
authors = ["bunnie <bunnie@kosagi.com>"]
description = "IME front end"
edition = "2018"
name = "ime-frontend"
version = "0.1.0"

# Dependency versions enforced by Cargo.lock.
[dependencies]
gam = {path = "../gam"}
graphics-server = {path = "../graphics-server"}
ime-plugin-api = {path = "../ime-plugin-api"}
keyboard = {path = "../keyboard"}
log = "0.4.14"
log-server = {package = "xous-api-log", path = "../../api/xous-api-log"}
ticktimer-server = {package = "xous-api-ticktimer", path = "../../api/xous-api-ticktimer"}
xous = { path = "../../xous-rs" }
locales = {path = "../../locales"}
xous-ipc = { path = "../../xous-ipc" }
xous-names = {package = "xous-api-names", path = "../../api/xous-api-names"}

num-derive = {version = "0.3.3", default-features = false}
num-traits = {version = "0.2.14", default-features = false}
rkyv = {version = "0.4.3", default-features = false, features = ["const_generics"]}

tts-frontend = {path="../tts"}

utralib = {path = "../../utralib", optional = true, default-features = false }

[features]
precursor = ["utralib/precursor", "xous/precursor"]
hosted = ["utralib/hosted"]
renode = ["utralib/renode", "xous/renode"]
tts = []
debugprint = []
default = [] # "debugprint"
