[package]
authors = ["bunnie <bunnie@kosagi.com>"]
description = "IME front end"
edition = "2018"
name = "ime-frontend"
version = "0.1.0"

# Dependency versions enforced by Cargo.lock.
[dependencies]
gam = {path = "../gam"}
graphics-server = {path = "../graphics-server"}
ime-plugin-api = {path = "../ime-plugin-api"}
keyboard = {path = "../keyboard"}
log = "0.4.14"
log-server = {version = "0.1.3", package = "xous-api-log"}
ticktimer-server = {path = "../ticktimer-server", package = "xous-ticktimer"}
xous = "0.9.9"
locales = {path = "../../locales"}
xous-ipc = "0.9.9"
xous-names = {version = "0.9.3", package = "xous-api-names"}

num-derive = {version = "0.3.3", default-features = false}
num-traits = {version = "0.2.14", default-features = false}
rkyv = {version = "0.4.3", default-features = false, features = ["const_generics"]}

tts-frontend = {path="../tts"}

utralib = {version = "0.1.3", optional = true, default-features = false }

[features]
precursor = ["utralib/precursor"]
hosted = ["utralib/hosted"]
renode = ["utralib/renode"]
tts = []
debugprint = []
default = [] # "debugprint"
