[package]
name = "totpbackup-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1.8"
ctaphid = "0.1.1"
cbor = {path = "../../libraries/cbor"}
hidapi = {version = "1.4.1", default_features = false}
serde_json = "1.0.82"
serde = {version = "1.0.138", features = ["derive"]}
hex = "0.4.3"
