[package]
name = "tts-frontend"
version = "0.1.0"
authors = ["bunnie <bunnie@kosagi.com>"]
edition = "2018"
description = "Text to speech integration server"

# Dependency versions enforced by Cargo.lock.
[dependencies]
xous = "0.9.9"
xous-ipc = "0.9.7"
log-server = { version = "0.1.1", package = "xous-api-log-server" }
ticktimer-server = { path = "../ticktimer-server" }
xous-names = { path = "../xous-names" }
log = "0.4.14"
num-derive = {version = "0.3.3", default-features = false}
num-traits = {version = "0.2.14", default-features = false}
rkyv = {version = "0.4.3", default-features = false, features = ["const_generics"]}
# xous-tts-backend = {path="../../../tts-backend"}
xous-tts-backend = "0.1.3"
codec = {path = "../codec"}

[target.'cfg(not(any(windows,unix)))'.dependencies]
utralib = { path = "../../utralib"}

[features]
tts = []
default = []
