[package]
name = "kernel-test"
version = "0.1.0"
authors = ["Sean Cross <sean@xobs.io>"]
edition = "2018"
description = "Program to test various aspects of the kernel"

# Dependency versions enforced by Cargo.lock.
[dependencies]
xous = "0.9.9"
log-server = { version = "0.1.1", package = "xous-api-log-server" }
ticktimer-server = { path = "../ticktimer-server" }
log = "0.4.14"

[target.'cfg(not(any(windows,unix)))'.dependencies]
utralib = { path = "../../utralib"}

[features]
default = []
