[package]
name = "kernel-test"
version = "0.1.0"
authors = ["Sean Cross <sean@xobs.io>"]
edition = "2018"
description = "Program to test various aspects of the kernel"

# Dependency versions enforced by Cargo.lock.
[dependencies]
xous = "0.9.9"
log-server = { version = "0.1.3", package = "xous-api-log" }
ticktimer-server = { version = "0.9.0", package = "xous-api-ticktimer" }
log = "0.4.14"

utralib = { version = "0.1.3", optional = true, default-features = false }

[features]
precursor = ["utralib/precursor"]
hosted = ["utralib/hosted"]
renode = ["utralib/renode"]
default = []
