[package]
name = "kernel-test"
version = "0.1.0"
authors = ["Sean Cross <sean@xobs.io>"]
edition = "2018"
description = "Program to test various aspects of the kernel"

# Dependency versions enforced by Cargo.lock.
[dependencies]
xous = "0.9.14"
log-server = { package = "xous-api-log", version = "0.1.8" }
ticktimer-server = { package = "xous-api-ticktimer", version = "0.9.6" }
log = "0.4.14"

utralib = { version = "0.1.3", optional = true, default-features = false }

[features]
precursor = ["utralib/precursor", "xous/precursor"]
hosted = ["utralib/hosted"]
renode = ["utralib/renode", "xous/renode"]
default = []
