[package]
name = "kernel-test"
version = "0.1.0"
authors = ["Sean Cross <sean@xobs.io>"]
edition = "2018"
description = "Program to test various aspects of the kernel"

# Dependency versions enforced by Cargo.lock.
[dependencies]
xous = { path = "../../xous-rs" }
log-server = { package = "xous-api-log", path = "../../api/xous-api-log" }
ticktimer-server = { package = "xous-api-ticktimer", path = "../../api/xous-api-ticktimer" }
log = "0.4.14"

utralib = { path = "../../utralib", optional = true, default-features = false }

[features]
precursor = ["utralib/precursor", "xous/precursor"]
hosted = ["utralib/hosted"]
renode = ["utralib/renode", "xous/renode"]
default = []
