[package]
authors = ["bunnie <bunnie@kosagi.com>"]
description = "Manage keyboard input"
edition = "2018"
name = "keyboard"
version = "0.1.0"

# Dependency versions enforced by Cargo.lock.
[dependencies]
log = {version = "0.4", features = ["max_level_trace", "release_max_level_trace"]}
log-server = {version = "0.1.1", package = "xous-api-log-server"}
ticktimer-server = {path = "../ticktimer-server"}
xous = "0.9.9"
xous-ipc = "0.9.9"
xous-names = {path = "../xous-names"}
llio = {path = "../llio"}
susres = {path = "../susres"}
spinor = {path = "../spinor"}

num-derive = {version = "0.3.3", default-features = false}
num-traits = {version = "0.2.14", default-features = false}
rkyv = {version = "0.4.3", default-features = false, features = ["const_generics"]}

[target.'cfg(not(any(windows,unix)))'.dependencies]
utralib = {path = "../../utralib"}

[features]
debugprint = []
debuginject = [] # used only if you want key injection via the UART
rawserial = []
braille = []
default = ["debuginject"] # "debugprint"
