[package]
name = "usb-test"
version = "0.1.0"
authors = ["bunnie <bunnie@kosagi.com>"]
edition = "2018"
description = "USB test & development stub"

# Dependency versions enforced by Cargo.lock.
[dependencies]
xous = { path = "../../xous-rs" }
log-server = { package = "xous-api-log", path = "../../api/xous-api-log" }
ticktimer-server = { package = "xous-api-ticktimer", path = "../../api/xous-api-ticktimer" }
xous-names = { package = "xous-api-names", path = "../../api/xous-api-names" }
log = "0.4.14"
num-derive = {version = "0.3.3", default-features = false}
num-traits = {version = "0.2.14", default-features = false}
susres = {package = "xous-api-susres", path = "../../api/xous-api-susres"}
keyboard = {path = "../keyboard"}
bitfield = "0.13.2"
vcell = "0.1.3"
utralib = { path = "../../utralib", optional = true, default-features = false }

usbd-human-interface-device = "0.1.1"
embedded-time = "0.12.1" # required by the keyboard interface

[dependencies.usb-device]
# see top level Cargo.toml for patch.crates-io directive to help with dev work
version = "0.2.8"
features=["log"]

[dev-dependencies]
rand = "0.7.3"
rand_chacha = "0.3.1"

[features]
precursor = ["utralib/precursor", "xous/precursor"]
hosted = ["utralib/hosted"]
renode = ["utralib/renode", "xous/renode"]
default = []
