[package]
authors = ["bunnie <bunnie@kosagi.com>"]
description = "Provide high-resolution, non-rollover system time"
edition = "2018"
name = "ticktimer-server"
version = "0.1.0"

# Dependency versions enforced by Cargo.lock.
[dependencies]
log = "0.4.14"
log-server = {version = "0.1.1", package = "xous-api-log-server"}
xous = "0.9.9"
xous-ipc = "0.9.7"
rkyv = {version = "0.4.3", default-features = false, features = ["const_generics"]}
num-derive = {version = "0.3.3", default-features = false}
num-traits = {version = "0.2.14", default-features = false}
susres = {path = "../susres"}
xous-names = {path = "../xous-names"}
xous-semver = "0.1.2"

[target.'cfg(not(any(windows,unix)))'.dependencies]
utralib = {path = "../../utralib"}

[target.'cfg(any(windows,unix))'.dependencies]

[features]
debug-print = []
watchdog = []
no-timestamp = [] # turns off embedded timestamp for reproducible builds
# you may want to remove the watchdog feature if you're debugging a crash, as it will force the system to reboot automatically
default = ["watchdog"]
# default = []
# default = ["debug-print"]
