[package]
authors = ["bunnie <bunnie@kosagi.com>"]
description = "Provide high-resolution, non-rollover system time"
edition = "2018"
name = "xous-ticktimer"
version = "0.1.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/betrusted-io/xous-core/"
homepage = "https://betrusted.io/xous-book/"

# Dependency versions enforced by Cargo.lock.
[dependencies]
xous-api-ticktimer = { version = "0.9.0" }
log = "0.4.14"
log-server = {version = "0.1.3", package = "xous-api-log"}
xous = "0.9.9"
xous-ipc = "0.9.9"
rkyv = {version = "0.4.3", default-features = false, features = ["const_generics"]}
num-derive = {version = "0.3.3", default-features = false}
num-traits = {version = "0.2.14", default-features = false}
susres = {version = "0.9.1", package = "xous-api-susres"}
xous-names = {version = "0.9.3", package = "xous-api-names"}
xous-semver = "0.1.2"

utralib = {version = "0.1.3", optional = true, default-features = false }


[features]
precursor = ["utralib/precursor", "susres/precursor"]
hosted = ["utralib/hosted", "susres/hosted"]
renode = ["utralib/renode", "susres/renode"]
debug-print = []
watchdog = []
no-timestamp = [] # turns off embedded timestamp for reproducible builds
# you may want to remove the watchdog feature if you're debugging a crash, as it will force the system to reboot automatically
default = ["watchdog"]
# default = []
# default = ["debug-print"]
