[package]
name = "xous-susres"
version = "0.1.13"
authors = ["bunnie <bunnie@kosagi.com>"]
edition = "2018"
description = "Manager of suspend/resume operations implementation"
license = "MIT OR Apache-2.0"
repository = "https://github.com/betrusted-io/xous-core/"
homepage = "https://betrusted.io/xous-book/"

# Dependency versions enforced by Cargo.lock.
[dependencies]
xous-api-susres = { path = "../../api/xous-api-susres" }
xous-names = { package = "xous-api-names", path = "../../api/xous-api-names" }
log-server = { package = "xous-api-log", path = "../../api/xous-api-log" }
xous = { path = "../../xous-rs" }
xous-ipc = { path = "../../xous-ipc" }
log = "0.4.14"

num-derive = {version = "0.3.3", default-features = false}
num-traits = {version = "0.2.14", default-features = false}
rkyv = {version = "0.4.3", default-features = false, features = ["const_generics"]}


utralib = { path = "../../utralib", optional = true, default-features = false }

[features]
precursor = ["utralib/precursor", "xous/precursor"]
hosted = ["utralib/hosted"]
renode = ["utralib/renode", "xous/renode"]
sus_reboot = [] # when selected, suspend triggers an immediate reboot instead of suspend. For testing only.
debugprint = []
default = []
