[package]
authors = ["Sean Cross <sean@xobs.io>"]
description = "Program to test various aspects of the kernel"
edition = "2018"
name = "rkyv-test-client"
version = "0.1.0"

# Dependency versions enforced by Cargo.lock.
[dependencies]
log = "0.4.14"
log-server = {path = "../log-server"}
rkyv-test-server = {path = "../rkyv-test-server"}
ticktimer-server = {path = "../ticktimer-server"}
xous = {path = "../../xous-rs"}
com = {path = "../com"}
xous-names = {path="../xous-names"}
susres = {path = "../susres"}

keyboard = {path="../keyboard"}

[features]
default = []
