[package]
authors = ["bunnie <bunnie@kosagi.com>"]
description = "Xous microkernel OS inter-process name resolution server"
edition = "2018"
name = "xous-names"
version = "0.9.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/betrusted-io/xous-core/"
homepage = "https://betrusted.io/"

# Dependency versions enforced by Cargo.lock.
[dependencies]
xous-api-names = {version = "0.9.2"}
num-derive = {version = "0.3.3", default-features = false}
num-traits = {version = "0.2.14", default-features = false}
log = "0.4.14"
log-server = {version = "0.1.3", package = "xous-api-log"}
xous = "0.9.9"
xous-ipc = "0.9.9"
rkyv = {version = "0.4.3", default-features = false, features = ["const_generics"]}

utralib = {version = "0.1.3", optional = true, default-features = false }

[target.'cfg(any(windows,unix))'.dependencies]

[features]
precursor = ["utralib/precursor"]
hosted = ["utralib/hosted"]
renode = ["utralib/renode"]
debugprint = []
default = [] # "debugprint"
