[package]
authors = ["bunnie <bunnie@kosagi.com>"]
description = "Xous microkernel OS inter-process name resolution server"
edition = "2018"
name = "xous-names"
version = "0.9.17"
license = "MIT OR Apache-2.0"
repository = "https://github.com/betrusted-io/xous-core/"
homepage = "https://betrusted.io/"

# Dependency versions enforced by Cargo.lock.
[dependencies]
xous-api-names = { path = "../../api/xous-api-names" }
log-server = {package = "xous-api-log", path = "../../api/xous-api-log"}
xous = { path = "../../xous-rs" }
xous-ipc = { path = "../../xous-ipc" }
num-derive = {version = "0.3.3", default-features = false}
num-traits = {version = "0.2.14", default-features = false}
log = "0.4.14"
rkyv = {version = "0.4.3", default-features = false, features = ["const_generics"]}

utralib = {path = "../../utralib", optional = true, default-features = false }

[target.'cfg(any(windows,unix))'.dependencies]

[features]
precursor = ["utralib/precursor", "xous/precursor"]
hosted = ["utralib/hosted"]
renode = ["utralib/renode", "xous/renode"]
debugprint = []
default = [] # "debugprint"
