[package]
name = "trng"
version = "0.1.0"
authors = ["bunnie <bunnie@kosagi.com>"]
edition = "2018"
description = "TRNG server"

# Dependency versions enforced by Cargo.lock.
[dependencies]
xous = "0.9.9"
log-server = { version = "0.1.3", package = "xous-api-log" }
ticktimer-server = { version = "0.9.1", package = "xous-api-ticktimer" }
xous-names = { version = "0.9.3", package = "xous-api-names" }
log = "0.4.14"
num-derive = {version = "0.3.3", default-features = false}
num-traits = {version = "0.2.14", default-features = false}
susres = {version = "0.9.1", package = "xous-api-susres"}
rkyv = {version = "0.4.3", default-features = false, features = ["const_generics"]}
xous-ipc = "0.9.9"

utralib = { version = "0.1.3", optional = true, default-features = false }

[target.'cfg(any(windows,unix))'.dependencies]
rand = "0.8.5"
rand_chacha = "0.3.1"

[features]
precursor = ["utralib/precursor"]
hosted = ["utralib/hosted"]
renode = ["utralib/renode"]
debugprint = []
avalanchetest = []
ringosctest = []
urandomtest = []
default = [] # "debugprint"
