[package]
authors = ["bunnie <bunnie@kosagi.com>"]
description = "COM interface to the EC"
edition = "2018"
name = "com"
version = "0.1.0"

# Dependency versions enforced by Cargo.lock.
[dependencies]
com_rs-ref = {path = "../../imports/com_rs-ref"}
log = "0.4.14"
log-server = {version = "0.1.2", package = "xous-api-log-server"}
ticktimer-server = {path = "../ticktimer-server"}
susres = {path = "../susres"}
typenum = "1.12"
xous = "0.9.9"
xous-ipc = "0.9.9"
xous-names = {path = "../xous-names"}
trng = {path = "../trng"}
llio = {path = "../llio"}

num-derive = {version = "0.3.3", default-features = false}
num-traits = {version = "0.2.14", default-features = false}
rkyv = {version = "0.4.3", default-features = false, features = ["const_generics"]}

xous-semver = "0.1.2"

[target.'cfg(not(any(windows,unix)))'.dependencies]
utralib = {path = "../../utralib"}

[target.'cfg(any(windows,unix))'.dependencies]

[features]
debugprint = []
default = [] # "debugprint"
fccagent = []
#default = ["debugprint"] # , "fccagent"
