[package]
authors = ["bunnie <bunnie@kosagi.com>"]
description = "COM interface to the EC"
edition = "2018"
name = "com"
version = "0.1.0"

# Dependency versions enforced by Cargo.lock.
[dependencies]
com_rs-ref = {path = "../../imports/com_rs-ref"}
log = "0.4.14"
log-server = {package = "xous-api-log", path = "../../api/xous-api-log"}
ticktimer-server = {package = "xous-api-ticktimer", path = "../../api/xous-api-ticktimer"}
susres = {package = "xous-api-susres", path = "../../api/xous-api-susres"}
typenum = "1.12"
xous = { path = "../../xous-rs" }
xous-ipc = { path = "../../xous-ipc" }
xous-names = {package = "xous-api-names", path = "../../api/xous-api-names"}
trng = {path = "../trng"}
llio = {path = "../llio"}

num-derive = {version = "0.3.3", default-features = false}
num-traits = {version = "0.2.14", default-features = false}
rkyv = {version = "0.4.3", default-features = false, features = ["const_generics"]}

xous-semver = "0.1.2"

utralib = {path = "../../utralib", optional = true, default-features = false }

[target.'cfg(any(windows,unix))'.dependencies]

[features]
precursor = ["utralib/precursor", "xous/precursor"]
hosted = ["utralib/hosted"]
renode = ["utralib/renode", "xous/renode"]
debugprint = []
default = [] # "debugprint"
fccagent = []
#default = ["debugprint"] # , "fccagent"
