[package]
name = "susres"
version = "0.1.0"
authors = ["bunnie <bunnie@kosagi.com>"]
edition = "2018"
description = "Manager of suspend/resume operations"

# Dependency versions enforced by Cargo.lock.
[dependencies]
xous = { path = "../../xous-rs" }
log-server = { path = "../log-server" }
xous-names = { path = "../xous-names" }
log = "0.4.14"

xous-ipc = {path="../../xous-ipc"}
num-derive = {version = "0.3.3", default-features = false}
num-traits = {version = "0.2.14", default-features = false}
rkyv = {version = "0.4.3", default-features = false, features = ["const_generics"]}


[target.'cfg(not(any(windows,unix)))'.dependencies]
utralib = { path = "../../utralib"}

[features]
sus_reboot = [] # when selected, suspend triggers an immediate reboot instead of suspend. For testing only.
debugprint = []
default = []
