[package]
name = "aes"
version = "0.8.1"
authors = ["bunnie <bunnie@kosagi.com>"]
edition = "2018"
description = "AES library for Xous"

# Dependency policy: fully specify dependencies to the minor version number
[dependencies]
xous = { path = "../../xous-rs" }
log-server = { path = "../log-server" }
log = "0.4.14"
hex-literal = "0.3.1"
cipher = "0.4.2"

[features]
hazmat     = [] # Expose cryptographically hazardous APIs
default = []