[package]
name = "aes"
version = "0.8.1"
authors = ["bunnie <bunnie@kosagi.com>"]
edition = "2018"
description = "AES library for Xous"

# Dependency versions enforced by Cargo.lock.
[dependencies]
xous = { path = "../../xous-rs" }
log-server = { package = "xous-api-log", path = "../../api/xous-api-log" }
log = "0.4.14"
hex-literal = "0.3.1"
cipher = "0.4.2"

[features]
hazmat     = [] # Expose cryptographically hazardous APIs
default = []