[package]
name = "aes"
version = "0.8.1"
authors = ["bunnie <bunnie@kosagi.com>"]
edition = "2018"
description = "AES library for Xous"

# Dependency versions enforced by Cargo.lock.
[dependencies]
xous = "0.9.9"
log-server = { version = "0.1.1", package = "xous-api-log-server" }
log = "0.4.14"
hex-literal = "0.3.1"
cipher = "0.4.2"

[features]
hazmat     = [] # Expose cryptographically hazardous APIs
default = []